name: fumeo
description: 'Fumeo'
publish_to: 'none'

version: 1.0.14+17

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  awesome_snackbar_content: ^0.1.4
  cupertino_icons: ^1.0.8
  dio: ^5.7.0
  flutter_highlighter: ^0.1.1
  flutter_image_compress: ^2.3.0
  flutter_markdown: ^0.7.5
  flutter_markdown_latex: ^0.3.4
  flutter_slidable: ^3.1.1
  fluttertoast: ^8.2.8
  get: ^4.6.6
  hive_ce: ^2.7.0+1
  hive_ce_flutter: ^2.1.0
  http: ^1.2.2
  image_picker: ^1.1.2
  intl: ^0.19.0
  markdown: ^7.2.2
  package_info_plus: ^8.1.0
  path_provider: ^2.1.5
  shared_preferences: ^2.3.5
  url_launcher: ^6.3.1
  webview_flutter: ^4.10.0
  yaml: ^3.1.2
  heroicons: ^0.11.0
  sqflite: ^2.4.1
  open_file: ^3.5.10
  permission_handler: ^11.3.1
  path: ^1.9.0
  flutter_syntax_view: ^4.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  hive_ce_generator: ^1.7.0

flutter:
  uses-material-design: true
  assets:
    - lib/images/
